### ISSUE TITLE
(Consumer) IllegalAccessException when using some unexpected types as state parameters

### ISSUE THREAD

**Issue by gaeljw** [jbwheatley/pact4s#607]
When changing the state parameters of one contract from a `Int` to a `Seq[Int]`, I've got the following exception on the consumer:

```
[info]   kotlin.reflect.full.IllegalCallableAccessException: java.lang.IllegalAccessException: class kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter cannot access a member of class scala.collection.immutable.$colon$colon with modifiers "private final"
[info]   at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:247)
[info]   at au.com.dius.pact.core.support.Utils.objectToJsonMap(Utils.kt:116)
[info]   at au.com.dius.pact.core.support.Utils.jsonSafeValue(Utils.kt:136)
[info]   at au.com.dius.pact.core.model.ProviderState.toMap(ProviderState.kt:20)
[info]   at au.com.dius.pact.core.model.RequestResponseInteraction.toMap(RequestResponseInteraction.kt:37)
[info]   at au.com.dius.pact.core.model.RequestResponsePact.toMap(RequestResponsePact.kt:31)
[info]   at au.com.dius.pact.core.model.DefaultPactWriter.writePact(PactWriter.kt:63)
[info]   at au.com.dius.pact.core.model.DefaultPactWriter.writePact(PactWriter.kt:111)
[info]   at au.com.dius.pact.consumer.BaseMockServer.verifyResultAndWritePact(MockHttpServer.kt:177)
[info]   at pact4s.RequestResponsePactForgerResources.verifyResultAndWritePactFiles(RequestResponsePactForgerResources.scala:39)
[info]   ...
[info]   Cause: java.lang.IllegalAccessException: class kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter cannot access a member of class scala.collection.immutable.$colon$colon with modifiers "private final"
[info]   at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
[info]   at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
[info]   at java.base/java.lang.reflect.Field.checkAccess(Field.java:1102)
[info]   at java.base/java.lang.reflect.Field.get(Field.java:423)
[info]   at kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter.call(CallerImpl.kt:161)
[info]   at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:107)
[info]   at au.com.dius.pact.core.support.Utils.objectToJsonMap(Utils.kt:116)
[info]   at au.com.dius.pact.core.support.Utils.jsonSafeValue(Utils.kt:136)
[info]   at au.com.dius.pact.core.model.ProviderState.toMap(ProviderState.kt:20)
[info]   at au.com.dius.pact.core.model.RequestResponseInteraction.toMap(RequestResponseInteraction.kt:37)
[info]   ...
```

Relevant code:
```scala
ConsumerPactBuilder
    ....
   .`given`("Some entities", Map("ids" -> Seq(123, 456)))
```

Sounds related to using Scala types that Pact JVM itself is not able to convert to a known Java type. Not necessarily a big issue, I just log it in case anyone face it as well.

**Comment by gaeljw** [comment]
Transforming the objects to Java (with standard Scala converters) works fine.

**Comment by jbwheatley** [comment]
yeah the state stuff was always a little janky/unsafe - I'll see what we can do to make it more usuable ootb

**Comment by jbwheatley** [comment]
think I fixed this on main, not release yet
